services:
  postgres:
    image: postgres:17
    container_name: odoo-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password
      POSTGRES_DB: odoo_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: